ALTER TABLE "source_cards"
ADD COLUMN IF NOT EXISTS "card_type" VARCHAR(50) NOT NULL DEFAULT 'topic',
ADD COLUMN IF NOT EXISTS "sources" JSONB,
ADD COLUMN IF NOT EXISTS "jls_sections" JSONB,
ADD COLUMN IF NOT EXISTS "module_sequence" JSONB,
ADD COLUMN IF NOT EXISTS "teach_after" JSONB,
ADD COLUMN IF NOT EXISTS "pedagogy_rules" JSONB,
ADD COLUMN IF NOT EXISTS "test_rules" JSONB,
ADD COLUMN IF NOT EXISTS "generation_rules" JSONB,
ADD COLUMN IF NOT EXISTS "approved_by" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "approved_at" TIMESTAMPTZ(6);
